#! /usr/bin/env python

import os,sys
import subprocess
import re
import shutil # for copying files
#from distutils.dir_util import copy_tree # for copying whole directories



## Parse and process command line arguments
sys.path.append("lib") # Standalone install

if os.path.exists("/usr/lib/iso-builder/lib"): # from deb pkg
   sys.path.append("/usr/lib/iso-builder/lib")

import parse_args
args_dict=parse_args.ib_parser()

#print args_dict
#print "ISO_DIR",args_dict['iso_name']

## Map the key:values of the args_dict into local variables
locals().update(args_dict)



def is_installed(CMD):
    cmd_install='sudo apt-get -y install '
    try: 
        subprocess.check_output('which ' + CMD,shell=True)
    except:
        sys.exit('ERROR: command '+ CMD + ' not found. \n Try:\n  ' + cmd_install + CMD)
    #print 'Command ' + CMD + ' is available'

#is_installed("ls")



## search and replace with regex. Similar to: sed -i 's/orig/final/' file 
def replace_in_file(search_str, replace_str, file_to_edit):
    orig_file = None
    with open(file_to_edit, 'r') as rfile :
        orig_file = rfile.read()
   
    search_str.encode('string-escape')
    replace_str.encode('string-escape')
    orig_file = re.sub(search_str, replace_str, orig_file, flags=re.M)

    with open(file_to_edit, 'w') as wfile:
        wfile.write(orig_file)






## Clear all files created by this script
def clean_all():
    if os.path.exists(tmp_edit_dir + 'isolinux'):
        subprocess.call(['chmod','-R','u+w', tmp_edit_dir]) 
        subprocess.Popen('rm -r ' + tmp_edit_dir ,shell=True).wait()
    if os.path.exists(tmp_mnt_dir + 'isolinux'):
        subprocess.Popen('fusermount -u ' + tmp_mnt_dir ,shell=True).wait()
        subprocess.Popen('rm -r ' + tmp_mnt_dir ,shell=True).wait()
   
## Create the directories to mount and extract the ISO file
def create_dirs():
    #print "tmp_mnt_dir = " +tmp_mnt_dir
    if not os.path.exists(tmp_mnt_dir):
        os.makedirs(tmp_mnt_dir)

    if not os.path.exists(iso_dir):
        os.makedirs(iso_dir)
    #subprocess.Popen('mkdir -p ' + tmp_mnt_dir ,shell=True).wait()
    #subprocess.Popen('mkdir -p ' + tmp_edit_dir ,shell=True).wait()

is_installed('fuseiso')

clean_all()
create_dirs() 



def ensure_iso_file():
 
    iso_files=[]
    for el in os.listdir(iso_dir):
        if el.endswith(('.iso','.ISO')):
            iso_files.append(el)

    #print "ISO_FILES", iso_files

    #print locals()
    if 'get_os' in globals():
        opsys=get_os.split("-")[0]    
        version=get_os.split("-")[1]
        version_dir=".".join(version.split(".")[0:2])
        iso_name="ubuntu-"+version+"-server-amd64.iso"
   
        for iso_n in iso_files:
            if opsys in iso_n and version in iso_n:
               print "ISO file " + iso_n + " found"
               download=False

        if not 'download' in locals():
            print "No iso file found for "+ opsys + version + ". Downloading..."
            file_url="http://releases.ubuntu.com/" + version_dir + "/" + iso_name
            print "Downloading from: ", file_url
            file_path = iso_dir + "/" + iso_name
            import urllib
            os_file = urllib.URLopener()
            os_file.retrieve(file_url, file_path)

        return iso_name

tmp=ensure_iso_file()
if tmp:
    iso_name=tmp



def check_integrity():
    ## So far, only for Ubuntu
    if iso_name.split("-")[0] == "ubuntu":
        version = iso_name.split("-")[1]
        version_dir = ".".join(version.split(".")[0:2])
        ## Fetch the cheksums file
        sums_fname="Ubuntu_"+version+"MD5SUMS"
        sums_path=iso_dir+sums_fname
        if not os.path.exists(sums_path):
            print "Downloading " + sums_fname + " checksums file"
            file_url="http://releases.ubuntu.com/" + version_dir + "/MD5SUMS"
            file_path = iso_dir + "/" + sums_fname
            import urllib
            os_file = urllib.URLopener()
            os_file.retrieve(file_url, file_path)
            

        import hashlib
        def hashfile(afile, hasher, blocksize=65536):
            buf = afile.read(blocksize)
            while len(buf) > 0:
                hasher.update(buf)
                buf = afile.read(blocksize)
            return hasher.hexdigest()

        this_hash = hashfile(open(iso_dir+iso_name, 'rb'), hashlib.md5())

        ## Check that this_hash matches the value in the MD5SUMS file
        for line in open(sums_path,"r"):
            if line.split("*")[1].rstrip() == iso_name:
                table_hash=line.split(" ")[0]
      
        if table_hash == this_hash:
            print "The " + iso_name + " file is OK"
        else:
            sys.exit("ERROR: The " + iso_dir+iso_name + " file is corrupted. Remove it and run this script again.")

check_integrity()





## Extract the original ISO file into the tmp_edit_dir folder
def extract_iso():
    subprocess.Popen('fuseiso ' + iso_dir + iso_name + ' ' + tmp_mnt_dir, shell=True).wait()
    #copy_tree(tmp_mnt_dir, tmp_edit_dir)
    #shutil.copytree(tmp_mnt_dir, tmp_edit_dir, symlinks=False)
    print "###Copying files"
    os.makedirs(tmp_edit_dir)
    ## Copy the content, not the directory. Otherwise we get a write permission error
    subprocess.Popen('rsync -aq ' + tmp_mnt_dir + '* ' + tmp_edit_dir, shell=True).wait()
    subprocess.Popen('rsync -aq ' + tmp_mnt_dir + '.disk ' + tmp_edit_dir, shell=True).wait()
    if 'cp_to_iso' in locals():
        subprocess.Popen('rsync -aq ' + cp_to_iso + ' ' + tmp_edit_dir, shell=True).wait()
    #subprocess.Popen('ls -la '+tmp_edit_dir, shell=True)
    print "###Copying done!"
    subprocess.call(['chmod','-R','u+w', tmp_edit_dir]) 


is_installed('rsync')
extract_iso()




def customize_kickstart():
    new_template='' # Var to avoid overwriting
    if not os.path.exists(args_dict['loc_kickstart_dir']):
        print 'Directory '+loc_kickstart_dir+' does not exist. Creating...'
        os.makedirs(args_dict['loc_kickstart_dir'])
 
    ## Make sure that we have a copy of the ks_template on the templates folder 
    path_use_template= loc_kickstart_dir + '/'+ 'ks_template.cfg'
    if not os.path.exists(path_use_template):
        print 'The file '+ path_use_template+' does not exist. Copying...'
        shutil.copy2(use_template,
                     path_use_template)

    ## Copy the template file to create our own kickstart 
    #ks_file = loc_kickstart_dir+'/'+template_name
    path_new_template= loc_kickstart_dir+ '/'+ template_name
    if not os.path.exists(path_new_template):
        print 'The file '+ path_new_template+' does not exist. Copying...'
        shutil.copy2(path_use_template, path_new_template)

    ## If the template already exists chose overwrite/rename
    else:
        print 'WARNING: the file ' + path_new_template + ' already exists.'
        print ' Do you want to overwrite it? Y = overwrite, N = rename, ' +\
              'everything else = exit'
        print ans_yes
        if ans_yes: # ans_yes is the cmd arg for "-y"
            answer="Y"
        else:
            answer=raw_input()

        if answer == "Y":
           shutil.copy2(path_use_template, path_new_template)
        elif answer == "N":
           print "Please provide a new name for the kicstart file:"
           new_name=raw_input()
           path_new_template = loc_kickstart_dir+ '/'+ new_name
           shutil.copy2(path_use_template, path_new_template)
           new_template=str(new_name)
        else:
           sys.exit("Exiting...")

 
    #path_template_name=loc_kickstart_dir+'/'+template_name
    #print "AAAAAAAA", path_template_name, path_new_template
    #if not os.path.exists(path_template_name):
    #     shutil.copy2(path_use_template,path_template_name) 

    ## Replace all the keys and values of the ks_values_dict on the new ks file 
    for key in ks_values_dict:
        #print key.pattern, ks_values_dict[key], path_template_name
        replace_in_file(key.pattern, ks_values_dict[key], path_new_template)  

    return new_template
   
 
new_template = customize_kickstart()
if new_template != '' and new_template != template_name:
   template_name = new_template



def edit_bootmenu():
    ks_file=loc_kickstart_dir+'/'+template_name
    shutil.copy2(ks_file,tmp_edit_dir)
    file_name=tmp_edit_dir + os.path.split(ks_file)[1]

    ## Change the default timeout for the menu
    cfg_file = args_dict['tmp_edit_dir'] + 'isolinux/isolinux.cfg'
    #subprocess.Popen("sed -i 's/timeout .*/timeout 100/'" + cfg_file ,shell=True)
    replace_in_file('timeout .*', 'timeout 100', cfg_file)

    ## Add the kickstart option as default
    menu_file = args_dict['tmp_edit_dir'] + 'isolinux/txt.cfg'
    replace_in_file('^default .*',
                    'default ks \\n'+
                    'label ks \\n'+
                    '  menu label ^KickStarted \\n'+
                    '  kernel /install/vmlinuz\\n'+
                    '  append  file=/cdrom/preseed/ubuntu-server.seed '+
                    'vga=788 initrd=/install/initrd.gz quiet '+
                    'ks=cdrom:/ks.cfg --- /',
                    menu_file
                   )


edit_bootmenu()

def rebuild_iso():
    ## This command looks something like:
    ## mkisofs -D -r -V "BOMSI_INSTALLER" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $OUT_ISO_DIR/$OUT_ISO_NAME $OUT_DIR/
    subprocess.Popen('mkisofs -quiet -D -r -V "BOMSI_INSTALLER" -cache-inodes -J -l ' + 
                      '-b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot ' +
                      '-boot-load-size 4 -boot-info-table '+
                      '-o ' + args_dict['out_iso_dir']+'/'+args_dict['out_iso_name'] + ' ' +
                       args_dict['tmp_edit_dir'],
                     shell=True
                     ).wait()

is_installed('genisoimage')
rebuild_iso()
print "###ISO file generated succesfully"

